controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    methods: ['GET']
    controller: App\Controller\SubscriberController

create_subscriber:
    path: /subscriber/new
    methods: ['POST']
    controller: App\Controller\SubscriberController::createSubscriber